//TODO: портировать в систему
loc={en:{}};
loc.en.errors={
	error_request_error: 'An error ocured during the request. Come back later.',
	error_page_not_found: 'Page not found.',
	error_stars: 'The stars is not on your side today.',
	error_forbidden: 'Access Forbidden!',
	error_not_enuoph_mana: 'Not enouph access rights or you may not be ',
	error_autorized: 'autorized',
	error_passwords_not_match: 'Passwords don\'t match',
	error_user_already_exists: 'User with that e-mail already exists',
	error_bad_token: 'Bad token',
	error_is_empty: 'Field is empty',
	error_bad_ip: 'Invalid IP-adress',
	error_bad_mail: 'Invalid e-mail',
	error_bad_name: 'Invalid name',
	error_bad_number: 'It is not a number',
	error_bad_integer: 'It is not an integer',
	error_bad_positive: 'It is not a positive number',
	error_bad_no_zero: 'It is a zero',
	error_bad_id: 'Invalid ID',
	error_bad_string_lenght: 'Invalid string lenght',
	error_bad_url: 'Invalid URL',
	error_bad_lang: 'Invalid lang name',
	error_bad_add_fields: 'All fields are empty or some field already exists',
	error_empty_field: 'Field is empty',
	error_reg_bad_confirmation: 'Invalid (or expired) actiovation code',
	error_login_success: 'You\'ve logged in.',
	error_login_user_not_found: 'User not found.',
	error_login_invalid_password: 'Invalid password.',
	error_login_autorization_overrun: 'To many autorization attempts.',
	error_login_ip_autorization_overrun: 'To many autorization attempts from your IP.',
	error_login_not_activated: 'Account is not activated.',
	error_login_request_error: 'Request error.',
	error_unknown_error: 'Unknown error',
	error_service_not_available: 'Sorry, service is not available.',
	error_invalid_start_end_time: 'Invalid start or end date/time.',
    error_bad_hash: 'Invalid media'
	}
loc.en.global={
	loc_current: 'English',
	loc_ru: 'Russian',
	loc_en: 'English',
	soc_top_communion: 'Communion',
	soc_top_calendar: 'Calendar',
	soc_top_catalog: 'Catalog',
	soc_top_connection: 'Connection',
	soc_top_tasks: 'Tasks',
	soc_top_finances: 'Finances',
	soc_top_bookmarks: 'Bookmarks',
	soc_top_moreservices: 'More services',

	page_main_hello: 'Main page. It is begging you to fill it with content.',
	page_main_exit_system: 'Exit the system',
	page_logout: 'Logout',
	page_enter: 'Enter',
	page_password: 'Password',
	page_password_repeat: 'Password confirmation',
	page_static_greeting: 'Caution! This page is static!',
	registration: 'Registration',
	page_login_title: 'Login',
	page_index_title: 'Home',
	page_404_title: '404',
	page_403_title: '403',
	page_fatal_error_title: 'Fatal Error',
	page_registration_title: 'Registration',
	page_registration_restiger: 'Registration',
	page_login: 'Login',
	page_profile_enternal: 'Profile',
	page_profile_enternal_edit: 'Profile edition',
	page_profile_enternal_title: 'Profile',
	page_profile_enternal_error_title: 'Profile not found',
	page_profile_enternal_edit_title: 'Edit profile',
	page_lost_password_title: 'Password changing',
	page_lost_password_instruction_text: 'Please, fill this fields and we will send you a link to generate a new password.',
	page_lost_password_header_text: 'Lost your password?',
	page_lost_password_sent_text: 'The link to generate a new password has been sent to your e-mail.',
	page_change_password_title: 'Password changing',
	page_password_changed_title: 'Password succesfuly changed',
	page_password_changed_header_text: 'Password succesfuly changed',
	page_password_changed_instruction_text: 'Now you can login: ',
	send: 'Send',
	new_password: 'New Password',
	logged_as: '',
	errors: 'Errors',
	vars: 'Variables',
	save: 'Save',
	male: 'Male',
	female: 'Female',
	sex: 'Sex',
	birth_date: 'Birth Date',
	first_name: 'First Name',
	last_name: 'Lastname',
	patronymic: 'Patronymic',
	invalid_birth_date: 'Invalid Birth Date',
	user_already_exists: 'User Already Exists',
	email_registration_notify_subject: 'E-forb.com - registration',
	email_registration_confirm_subject: 'Activation required',

	user_id: 'User ID',

	religion: 'Religion',
	marital_status: 'Marital Status',
	marital_married: 'Married',
	marital_not_married: 'Not Married',
	page_profile_enternal_info: 'General information',

	user_not_found: 'User is not found',

	time_ago: 'ago',
	time_after: 'after',
	time_now: 'now',
	time_half_an_hour: 'half an hour',
	time_today: 'today',
	time_yesturday: 'yesturday',
	time_tommorow: 'tommorow',
	time_minutes: 'minutes',
	time_minutes_a: 'minutes',
	time_minutes_u: 'a minute',
	time_half_a_minute: 'half a minute',
	time_hour: 'hour',
	time_hours: 'hours',
	time_day: 'day',
	time_days_a: 'days',
	time_days: 'days',
	time_at: 'at',
	time_in: 'in',
	time_month_1: 'of january',
	time_month_2: 'of february',
	time_month_3: 'of march',
	time_month_4: 'of april',
	time_month_5: 'of may',
	time_month_6: 'of june',
	time_month_7: 'of july',
	time_month_8: 'of august',
	time_month_9: 'of september',
	time_month_10: 'of october',
	time_month_11: 'of novermber',
	time_month_12: 'of december',

	widget_friends_title: 'Friends',
	widget_friends_online_title: 'Friends on-line',
	widget_members_title: 'Members',
	widget_members_online_title: 'Members on-line',
	widget_group_administration_title: 'Group administration',
	widget_event_administration_title: 'Event administration',

	widget_people_list_men: 'people',
	widget_people_list_men_1: 'people',
	widget_people_list_men_a: 'people',

	button_add_friend: 'Add to friend-list',
	button_remove_friend: 'Remove from friend-list',
	button_cancel_friend: 'Cancel friend request',
	button_cancel_group: 'Cancel group request',
	button_cancel_event: 'Cancel event request',
	its_you: 'It is you',
	button_write_message: 'Write a message',


	to_search: 'Search!',
	search: 'Search',

	page_search_friend_firstname_or_lastname: 'Firstname or lastname',
	page_search_group_name_placeholder: 'Group name',
	page_search_friend_title: 'Friend search',
	page_search_group_title: 'Group search',
	page_search_no_results: 'Nothing found',

	page_search_event_name_placeholder: 'Event name',
	page_search_event_title: 'Event search',

	page_feed_title: 'News',
	page_feed_profile_edited: 'You have edited your profile.',

	button_join_group: 'Join group',
	button_quit_group: 'Quit group',
	button_request_group: 'Send request',
	button_request_event: 'Send request',
	group: 'Group',
	page_group_description: 'Description',
	page_group_not_found_title: 'Group is not found.',

	button_join_event: 'Join event',
	button_quit_event: 'Quit event',
	event: 'event',
	page_event_description: 'Description',
	page_event_not_found_title: 'Event is not found.',

	social_social_network: 'Social Network',

	added_to_friends: 'Added to friendlist.',
	button_accept_friend: 'Accept friend',
	button_decine_friend: 'Decine friend',
	button_add_user_to_blacklist: 'Add to blacklist',
	button_add_user_to_banlist: 'Add to banlist',
	button_remove_user_from_blacklist: 'Remove from blacklist',
	button_remove_user_from_ban: 'Remove from banlist',
	page_friend_requests_title: 'Friendship requests',
	page_friend_requests_no_requests: 'No friendship requests found',

	page_frined_black_list_empty: 'You have no users in your black list',
	page_frined_ban_list_empty: 'You have no users in your ban list',

	page_friend_list_title: 'Friends list',
	page_friend_online_list_title: 'Users online',
	page_friend_black_list_title: 'Black list',
	page_friend_ban_list_title: 'Ban list',
	page_friend_list_no_friends: 'You have no freinds.',
	page_friend_list_no_friends_online: 'You have no freinds online.',
	page_people_list_no_friends: 'You have no freinds.',
	page_people_list_empty: 'List empty.',
	page_people_list_no_friends_online: 'You have no freinds online.',
	page_people_list_no_members: 'You have no freinds.',
	page_people_list_no_members_online: 'You have no freinds online.',

	page_search_list_people: 'People',

	page_groups_list_title: 'Groups list',
	page_groups_list_no_groups: 'You don\'t consist in any group',
	page_groups_list_no_groups_requests: 'No groups invites',
	page_groups_list_groups: 'Groups',
	page_groups_list_requests: 'Invites',
	page_groups_list_search_groups: 'Search groups',
	page_groups_list_add_group: 'New group',
	page_group_edit_title: 'Edit group',
	page_group_add_title: 'New group',


	page_events_list_title: 'Events list',
	page_events_list_no_events: 'You don\'t go to any event',
	page_events_list_no_events_requests: 'No invites',
	page_events_list_events: 'Events',
	page_events_list_requests: 'Invites',
	page_events_list_search_events: 'Events search',
	page_events_list_add_event: 'Add event',
	page_event_edit_title: 'Edit event info',
	page_event_add_title: 'Add event',

	page_user_blog_empty_title: 'Блог пользователя',
	page_group_blog_empty_title: 'Блог группы',

	title: 'Title',
	description: 'Description',


	edt: 'edit',
	menu_my_page: 'My profile',
	menu_my_friends: 'My friedns',
	menu_my_messages: 'My messages',
	menu_my_clubs: 'My clubs',
	menu_my_events: 'My events',
	menu_feed: 'News',
	menu_my_photos: 'My photos',
	menu_my_audio: 'My audio',
	menu_my_video: 'My video',
	menu_settings: 'My settings',

	block_quick_search_search: 'Serch by site',
	block_quick_search_to_find: 'Find!',

	error_service_not_available: 'Sorry, service is not available.',

	page_index_describe_header: 'Social network. File storage. The system of customer relationship management. Eforb - we are open to everyone!',
	page_index_describe_text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an  unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,  remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop  publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
	widget_greeting_social_network: 'Social Network',
	widget_greeting_free_crm: 'Free CRM',
	widget_greeting_filebox: 'Eforb filebox',
	widget_greeting_open_api: 'Eforb Open API',
	widget_greeting_buisness_platform: 'Busness Network',
	Widget_greeting_social_network_description: 'universal means of communication and finding friends. You can look at people, show off, share ideas, find out what\'s new with old friends and new friends to look. ',
	Widget_greeting_free_crm_description: 'powerful CRM-system, which allows you to centrally manage: information about customers, sales, purchasing, finance, human resources and tasks. Is an indispensable assistant managers, increasing their effectiveness. Enables the manager to analyze and control the business. ',
	Widget_greeting_filebox_description: 'Eforb filebox - free easy way to synchronize files between the devices',
	Widget_greeting_open_api_description: 'You can create any app and use the API Eforb to access and exchange information with servers Eforb. You can use any number of your own servers or by any means to monetize their own applications. API provides developers with hundreds of features and allows you to create interesting, interactive and popular applications. ',
	Widget_greeting_buisness_platform_description: 'Business platform enables centralized control: customer information, sales, purchasing, finance, human resources and tasks.',

	page_index_join_the_team: 'Join the team!',

	page_messages_title: 'Messages',
	page_messages_incoming_title: 'Incoming',
	page_messages_outcoming_title: 'Outcoming',
	page_messages_from_user_title: 'Messages from user',
	page_messages_awnser: 'Awnser',
	page_messages_write: 'Write',
	page_messages_subject: 'Subject',
	page_messages_text: 'MEssage text',
	page_messages_reciever: 'Reciever',
	page_messages_symbols_left: 'Symbols left: ',
	page_messages_symbols_overprint: 'Symbols limit exeeded by: ',
	page_messages_history: 'Message history',
	page_messages_write_a_message: 'Write a message',
	page_messages_delete: 'Delete',
	page_messages_no_messages: 'You have no messages',
	page_messages_message_for: 'Message for: ',

	page_messages_edit_private_who_can_write_me: 'Who can write me?',
	page_messages_edit_private_no_one: 'No one',
	page_messages_edit_private_friends: 'Friends',
	page_messages_edit_private_all: 'Everyone',
	page_profile_private_edit_title: 'Private settings',


	//EVENT_UPDATE_PROFILE = 0x02
	feed_update_profile: 'You have updated your profile.',
	//EVENT_FRIEND_ACCEPT = 0x04
	feed_friendship: ' is now friends',
	//EVENT_GROUP_JOIN = 0x08
	feed_join_group: 'has joined group ',
	//EVENT_GROUP_QUIT = 0x09
	feed_quit_group: 'has qutied group ',
	//EVENT_EVENT_JOIN = 0x11
	feed_join_event: 'has joined event ',
	//EVENT_EVENT_QUIT = 0x12
	feed_quit_event: 'has quited event ',

	loc_and: 'and',


	//WIDGET WALL
	wall: 'Wall',
	widget_wall_whats_new: 'What\'s new?',
	widget_wall_public_message: 'Public message',
	widget_wall_to_comment: 'Comment',
	widget_wall_comment_placeholder: 'Put your comment here',
	widget_wall_allposts: 'All posts',
	widget_wall_favorites: 'Favorites',
	widget_wall_photo: 'Photo',
	widget_wall_video: 'Video',
	widget_wall_audio: 'Audio',
	widget_wall_references: 'References',
	widget_wall_polls: 'Polls',

	edit_event: 'Edit event',
	edit_group: 'Edit group',

	page_event_not_found_title: 'Event not found',
	page_group_not_found_title: 'Group not found',

	edit_members: 'Edit members',
	invite: 'Invite',
	edit_administration: 'Edit admins',

	event_place: 'Place',
	event_end_date: 'Finishs on',
	event_start_date: 'Starts on',
	event_city: 'City',
	event_type: 'Type',

	loc_delete: 'Delete',

	page_group_members_title: 'Members',
	page_group_requests_title: 'Requests',
	page_group_administration_title: 'Group administration',
	page_group_invite_title: 'Invite',

	page_event_members_title: 'Members',
	page_event_administration_title: 'Event administration',
	page_event_invite_title: 'Invite',
	page_people_list_members: 'Members',
	page_people_list_invite: 'Invite',
	page_people_list_invites: 'Manage invites',
	page_people_list_requests: 'Manage requests',
	page_people_list_administration: 'Administration',
	page_people_list_remove_invite: 'Decline invite',
	page_people_list_remove_from_administation: 'Remove from administration',
	page_people_list_remove_member: 'Remove member',
	page_people_list_accept_request: 'Accept request',
	page_people_list_decline_request: 'Decline request',
	page_people_list_add_to_administation: 'Add to administration',

	pagination_page: 'Page',
	pagination_next_page: 'Next page',
	pagination_previous_page: 'Previuos pages',
	pagination_last_page: 'Last page',
	pagination_first_page: 'First page',
	pagination_more: 'More',
	pagination_show_more: 'Show more',

	link_more: 'More',

	group_private: 'Closed (private) group',

	//LISTS
	family: 'Family',
	work: 'Work',
	school: 'School',
	page_friends_add_list: 'Add list',
	page_friends_add: 'Add',
	page_friends_list_name: 'List name',

	page_friend_list_editor_edit_list: 'Edit list',
	page_friend_list_editor_delete_list: 'Delete list',
	page_friend_list_editor_view_list: 'View list',

	page_groups_requests_title: 'Requests',
	button_accept_group: 'Accept invite',
	button_decline_group: 'Decline',

	page_photo_title: 'Photo',
	page_media_next: 'Next',
	page_media_previous: 'Previous',
	page_media_upload: 'Upload',
	page_media_upload_more: 'Upload more',
	page_media_album: 'Album',
	page_photo_album: 'Album',
	page_audio_album: 'Playlist',
	page_video_album: 'Video collection',
	page_audio_title: 'Audio',
	page_audio_record: 'Audio',
	page_video_title: 'Video',
	page_video_record: 'Video',

	loc_edit: 'Edit',
	uploaded: 'Uploaded',
	author: 'Author',
	added: 'Added',
	changed: 'Changed',
	pin_some_people: 'Pin people',
	page_photo_album_edit_title: 'Edit album',
	page_photo_edit_title: 'Edit photos in album',
	page_photo_album_edit_title: 'Edit album',
	page_album_edit_title: 'Edit album',
	page_photo_album_delete: 'Delete album',
	page_photo_album_add: 'Add album',
	page_photo_album_add_title: 'Add album',
	page_photo_make_cover: 'Make this photo the album\'s cover',
	page_photo_no_photos: 'There is no photos yet.',
	page_photo_no_albums: 'There is no albums yet.',
	page_photo_add_title: 'Add photos',
	page_photo_no_pin_friends: 'You have no friends to pin to this photo',

	page_audio_album_delete: 'Delete playlist',
	page_audio_album_add: 'Add playlist',
	page_audio_album_add_title: 'Add playlist',
	page_audio_no_audios: 'There is no audios yet.',
	page_audio_no_albums: 'There is no playlists yet.',
	page_audio_add_title: 'Add audios',
	page_audio_edit: 'Edit audio',
	page_audio_all_albums: 'Playlists',
	page_audio_album_edit_title: 'Playlist editing',

	page_video_album_edit_title: 'Edit collection',
	page_video_edit_title: 'Edit videos in collection',
	page_video_album_edit_title: 'Edit collection',
	page_video_album_delete: 'Delete collection',
	page_video_album_add: 'Add collection',
	page_video_album_add_title: 'Add collection',
	page_video_make_cover: 'Make this video the collection\'s cover',
	page_video_no_videos: 'There is no videos yet.',
	page_video_no_albums: 'There is no collections yet.',
	page_video_add_title: 'Add videos',
	page_video_no_pin_friends: 'You have no friends to pin to this video',
	page_video_back_to_album: 'Back to collection',
	page_video_all_albums: 'Collections',
	page_video_default_title: 'All videos',
	page_video_album_edit: 'Edit colletion',

	widget_photo_albums_title: 'Photo albums',

	widget_photo_album: 'album',
	widget_photo_albums: 'albums',
	widget_photo_albums_1: 'albums',
	widget_photo_albums_a: 'albums',

	total: 'Total',
	widget_photo_album_no_cover: 'Album',
	widget_photo_title: 'Photo',
	widget_audio_title: 'Audio',
	widget_video_title: 'Video',
	widget_video_no_videos: 'There is no video here. ',
	widget_audio_no_audios: 'There is no audio here. ',
	widget_photo_no_photos: 'There is no photo here. ',
	widget_photo_albums_no_albums: 'There is no albums here. ',

	page_photo_tag_its_you: 'Photos with you',
	page_photo_tag_title: 'Photos with ',

	page_discussion_add_title: 'Add new discussion',
	page_discussion_edit_title: 'Edit discussion',
	page_discussion_start_from_parent: 'Started from discussion',
	page_discussion_all_in_group: 'all discussions in group',
	page_discussion_groups_all: 'Discussions of group ',
	to_view: 'View',

	page_calendar_events: 'You want to go to',
	page_calendar_title: 'Calendar',
	page_calendar_no_events_this_month: 'No events are in plans this month',
	page_calendar_birthdays: 'Your friends have birthday',

	month_1: 'january',
	month_2: 'february',
	month_3: 'march',
	month_4: 'april',
	month_5: 'may',
	month_6: 'june',
	month_7: 'july',
	month_8: 'august',
	month_9: 'september',
	month_10: 'october',
	month_11: 'novermber',
	month_12: 'december',

	page_discussion_no_discussions: 'There are no discussions here',
	widget_discussions_no_discussions: 'There are no discussions here',
	widget_discussions_title: 'Discussions',

	widget_poll_title: 'Poll',
	widget_poll_add: 'Add poll',
	widget_poll_new_answer: 'Add answer',
	widget_poll_add_title: 'Poll\'s description',
	widget_poll_to_vote: 'Vote!',

	page_post_edit_title: 'Edit post ',
	page_post_add_title: 'Add new post ',
	page_blog_edit_title: 'Edit blog ',
	page_blog_not_found_title: 'Blog is not found',
	page_blog_blog: 'Blog',
	page_blog_comments: 'Comments',
	page_blog_add_new_post: 'Compose new post',
	page_blog_no_posts: 'No posts here',

	menu_my_calendar: 'My Calendar',
	menu_my_blog: 'My Blog',

	photo_with: 'Photo with',
	video_with: 'Video with',
	announce_event: 'Tell about event',
	announce_group: 'Tell about group',
	announce: 'Tell friends',

	feed_user_was_tagged: ' were tagged on: ',
	feed_audio_album: 'Playlist',
	feed_video_album: 'Video collection',
	feed_photo_album: 'Photo album',
	feed_in_blog: 'in blog',
	feed_blog_post: 'Post',
	feed_blog: 'Blog',
	feed_discussion: 'Discussion',
	feed_show_same: 'Show similar',
	feed_hide_same: 'Hide similar',
	widget_poll_add_poll: 'Add poll',

	widget_blog_title: 'Blog',
	widget_blog_no_posts: 'No posts here',

	page_photo_you_was_tagged: ' You was tagged to photo ',
	page_video_you_was_tagged: ' You was tagged to video ',
	page_photo_has_tagged_you: ' has tagged you on photo ',
	page_video_has_tagged_you: ' has tagged you on video ',
	page_tagged_acsept: 'Acsept',
	page_tagged_decline: 'Decline',
	loc_someone: 'Someone',


	attach_button: 'Attach',
	attach_photo: 'Photo',
	attach_photo_album: 'Photo album',
	attach_video: 'Video',
	attach_audio: 'Audio',
	attach_poll: 'Poll',
	attach_map: 'Map',

	enable_delayed_message: 'Send this message ',
	send_delayed_message_after: 'Send at: ',

	enable_poll: 'Add poll',

	loc_at: 'at',

	widget_like_delete: 'I don\'t like',
	widget_like_add: 'I like',
	widget_like_people_liked: 'These people like',

	page_feed_privacy_edited: 'You have changed privacy settings.',

	upload_avatar: 'Upload a new photo',

	group_access_type: 'Group type',
	group_access_public: 'Public',
	group_access_restricted: 'Restricted',
	group_access_private: 'Private',
	event_access_type: 'Event type',
	event_access_public: 'Public',
	event_access_restricted: 'Restricted',
	event_access_private: 'Private',
	group_wall_mode: 'Wall',
	wall_off: 'Off',
	wall_public: 'Opened',
	wall_restricted: 'Restricted',
	wall_private: 'Closed',
	group_video_mode: 'Video',
	video_off: 'Off',
	video_public: 'Opened',
	video_restricted: 'Restricted',
	group_audio_mode: 'Audio',
	audio_off: 'Off',
	audio_public: 'Opened',
	audio_restricted: 'Restricted',
	group_photo_mode: 'Photos',
	photo_off: 'Off',
	photo_public: 'Opened',
	photo_restricted: 'Restricted',
	group_blog_mode: 'Blog',
	blog_off: 'Off',
	blog_public: 'On',
	group_discussions_mode: 'Duscussions',
	discussions_off: 'Off',
	discussions_public: 'On',
	
	page_messages_mark_as_viewed: 'Mark as viewed'
	}
