//TODO: портировать в систему
loc={ru:{}};
loc.ru.errors={
	error_request_error: 'При обработке запроса возникла ошибка. Попробуйте зайти позже.',
	error_page_not_found: 'Страница не найдена.',
	error_stars: 'Возможно звезды сегодня не нашей стороне.',
	error_forbidden: 'Доступ запрещен!',
	error_not_enuoph_mana: 'Недостаточно прав доступа или может быть вы просто не ',
	error_autorized: 'авторизованы',
	error_passwords_not_match: 'Пароли не совпадают',
	error_user_already_exists: 'Пользователь с таким e-mail уже существует',
	error_bad_token: 'Некорректный токен',
	error_is_empty: 'Пустое знаечение',
	error_bad_ip: 'Некорректный IP-адрес',
	error_bad_mail: 'Некорректный e-mail',
	error_bad_name: 'Некорректное имя',
	error_bad_number: 'Это не число',
	error_bad_integer: 'Это не целое число',
	error_bad_positive: 'Это не положительное число',
	error_bad_no_zero: 'Это ноль',
	error_bad_id: 'Это не ID',
	error_bad_string_lenght: 'Некорректная длина строки',
	error_bad_url: 'Некорректный url',
	error_bad_lang: 'Некорректное сокращение названия языка',
	error_bad_add_fields: 'Ни одно поле не заполнено или какое-то из полей уже существует',
	error_empty_field: 'Пустое поле',
	error_reg_bad_confirmation: 'Неверный, просроченный или уже использованный код активации',
	error_login_success: 'Вы успешно вошли в систему.',
	error_login_user_not_found: 'Пользователь не найден.',
	error_login_invalid_password: 'Неверный пароль.',
	error_login_autorization_overrun: 'Превышено количество попыток авторизации.',
	error_login_ip_autorization_overrun: 'Слишком много попыток авторизации с вашего IP.',
	error_login_not_activated: 'Аккаунт не активирован.',
	error_login_request_error: 'Ошибка запроса. Вы случайно не пытаетесь нас взломать? :)',
	error_unknown_error: 'Неизвестная ошибка',
	error_service_not_available: 'Приносим извинения. В данный момент сервис недоступен.',
	error_invalid_start_end_time: 'Некорректно выбрано вмремя начала/окончания встречи.',
    error_bad_hash: 'Некорректный файл'
	}
	
loc.ru.global={
	loc_current: 'Русский',
	loc_ru: 'Русский',
	loc_en: 'Английский',
	soc_top_communion: 'Общение',
	soc_top_calendar: 'Календарь',
	soc_top_catalog: 'Каталог',
	soc_top_connection: 'Знакомства',
	soc_top_tasks: 'Задачи',
	soc_top_finances: 'Финансы',
	soc_top_bookmarks: 'Закладки',
	soc_top_moreservices: 'Ещё сервисы',
	
	page_main_hello: 'Главная страница. Она так и просит,что бы кто-нибудь заполнил её контентом.',
	page_main_exit_system: 'Выйти из системы',
	logout: 'Выйти',
	enter: 'Войти',
	password: 'Пароль',
	password_repeat: 'Подтверждение пароля',
	page_static_greeting: 'Осторожно! Эта страница статическая!',
	registration: 'Регистрация',
	page_login_title: 'Вход',
	page_index_title: 'Главная',
	page_404_title: 'Ошибка 404',
	page_403_title: 'Ошибка 403',
	page_fatal_error_title: 'Ошибка',
	page_registration_title: 'Регистрация',
	page_profile_enternal_title: 'Профиль',
	page_profile_enternal_error_title: 'Профиль не найден',
	page_profile_enternal_edit_title: 'Редактирование профиля',
	page_registration_restiger: 'Зарегистрироваться',
	page_login: 'Логин',
	page_profile_enternal: 'Профиль',
	page_profile_enternal_edit: 'Редактирование профиля',
	logged_as: 'Вы зашли, как',
	errors: 'Ошибки',
	vars: 'Переменные',
	save: 'Сохранить',
	add: 'Добавить',
	male: 'Мужской',
	female: 'Женский',
	sex: 'Пол',
	birth_date: 'Дата рождения',
	first_name: 'Имя',
	last_name: 'Фамилия',
	patronymic: 'Отчество',
	invalid_birth_date: 'Некорректная дата рождения',
	user_already_exists: 'Пользователь уже существует',
	email_registration_notify_subject: 'E-forb.com - регистрация',
	email_registration_confirm_subject: 'Требуется активация',
	registration_required_confirm: 'Вы были успешно зарегистрированы. На ваш email придет письмо с инструкциями для активации учетной записи.',
	registration_done: 'Регистрация завершена. Вы можете войти на сайт,используя свой email и пароль.',

	user_id: 'Пользователь ',

	religion: 'Вероисповедание',
	marital_status: 'Семейный статус',
	marital_married: 'в браке',
	marital_not_married: 'не в браке',
	page_profile_enternal_info: 'Общая информация',


	time_ago: 'назад',
	time_after: 'через',
	time_now: 'сейчас',
	time_half_an_hour: 'полчаса',
	time_today: 'сегодня',
	time_yesturday: 'вчера',
	time_tommorow: 'завтра',
	time_minutes: 'минут',
	time_minutes_a: 'минуты',
	time_minute_u: 'минуту',
	time_half_a_minute: 'пол минуты',
	time_hour: 'час',
	time_hours: 'часа',
	time_day: 'день',
	time_days_a: 'дня',
	time_days: 'дней',
	time_at: 'в',
	time_in: 'в',
	time_month_1: 'января',
	time_month_2: 'февраля',
	time_month_3: 'марта',
	time_month_4: 'апреля',
	time_month_5: 'мая',
	time_month_6: 'июня',
	time_month_7: 'июля',
	time_month_8: 'августа',
	time_month_9: 'сентября',
	time_month_10: 'октября',
	time_month_11: 'ноября',
	time_month_12: 'декабря',

	page_lost_password_title: 'Восстановление пароля',
	page_lost_password_instruction_text: 'Заполните поля и мы вышлем ссылку для смены пароля вам на почту.',
	page_lost_password_header_text: 'Забыли пароль?',
	page_lost_password_sent_text: 'Ссылка для генерации нового пароля выслана вам на почту',
	page_change_password_title: 'Смена пароля',
	page_password_changed_title: 'Пароль изменён',
	page_password_changed_header_text: 'Пароль успешно сменён',
	page_password_changed_instruction_text: 'Сейчас вы можете ',
	change_password: 'Сменить пароль',
	send: 'Отправить',
	new_password: 'Новый пароль',

	widget_friends_title: 'Друзья',
	widget_friends_online_title: 'Друзья онлайн',
	widget_members_title: 'Участники',
	widget_members_online_title: 'Участники онлайн',
	widget_group_administration_title: 'Администрация группы',
	widget_event_administration_title: 'Администрация встречи',

	widget_people_list_men: 'людей',
	widget_people_list_men_1: 'человек',
	widget_people_list_men_a: 'человека',

	button_add_friend: 'Добавить в друзья',
	button_remove_friend: 'Удалить из друзей',
	button_cancel_friend: 'Отменить заявку',
	button_cancel_group: 'Отменить заявку',
	button_cancel_event: 'Отменить заявку',
	its_you: 'Это вы',
	button_write_message: 'Написать сообщение',


	to_search: 'Искать',
	search: 'Поиск',

	page_search_friend_firstname_or_lastname: 'Имя или фамилия',
	page_search_friend_title: 'Поиск друзей',
	page_search_group_name_placeholder: 'Название группы',
	page_search_group_title: 'Поиск групп',
	page_search_event_name_placeholder: 'Название встречи',
	page_search_event_title: 'Поиск встреч',
	page_search_no_results: 'Ни чего не найдено',

	page_feed_title: 'Новости',
	page_feed_profile_edited: 'Вы отредактировали свой профиль.',

	button_join_group: 'Вступить в группу',
	button_quit_group: 'Выйти из группы',
	button_request_group: 'Подать заявку',
	button_request_event: 'Подать заявку',
	group: 'Группа',
	page_group_description: 'Описание',
	page_group_not_found_title: 'Группа не найдена.',

	button_join_event: 'Пойти на встречу',
	button_quit_event: 'Не идти на встречу',
	event: 'Встреча',
	page_event_description: 'Описание',
	page_event_not_found_title: 'Встреча не найдена.',

	social_social_network: 'Социальная сеть',

	added_to_friends: 'Добавлен в друзья',
	button_accept_friend: 'Принять запрос',
	button_decine_friend: 'Отклонить запрос',
	button_add_user_to_blacklist: 'В чёрный список',
	button_add_user_to_banlist: 'Забанить',
	button_remove_user_from_blacklist: 'Удалить из чёрного списка',
	button_remove_user_from_ban: 'Удалить из бан-листа',
	page_friend_requests_title: 'Запросы дружбы',
	page_friend_requests_no_requests: 'Нет запросов на добавление в друзья',

	page_frined_black_list_empty: 'В вашем чёрном списке еще ни кого нет',
	page_frined_ban_list_empty: 'В вашем бан-листе еще ни кого нет',

	page_friend_list_title: 'Список друзей',
	page_friend_online_list_title: 'Пользователи он-лайн',
	page_friend_black_list_title: 'Чёрный список',
	page_friend_ban_list_title: 'Бан-лист',
	page_friend_list_no_friends: 'У вас нет друзей.',
	page_friend_list_no_friends_online: 'У вас нет друзей online.',
	page_people_list_no_friends: 'У вас нет друзей.',
	page_people_list_empty: 'Список пуст.',
	page_people_list_no_friends_online: 'У вас нет друзей online.',
	page_people_list_no_members: 'Сейчас нет участников.',
	page_people_list_no_members_online: 'Сейчас нет участников online.',

	page_search_list_people: 'Люди',

	page_groups_list_title: 'Список групп',
	page_groups_list_no_groups: 'Вы не состоите ни в одной группе.',
	page_groups_list_no_groups_requests: 'Вам не поступило приглашений в группы.',
	page_groups_list_groups: 'Группы',
	page_groups_list_requests: 'Приглашения',
	page_groups_list_search_groups: 'Поиск групп',
	page_groups_list_add_group: 'Создать группу',
	page_group_edit_title: 'Редактирование группы',
	page_group_add_title: 'Создание группы',

	page_events_list_title: 'Список встреч',
	page_events_list_no_events: 'Вы не участвуете ни в одной встрече.',
	page_events_list_no_events_requests: 'Вам не поступили приглашения на встречи.',
	page_events_list_events: 'Встречи',
	page_events_list_requests: 'Приглашения',
	page_events_list_search_events: 'Поиск встреч',
	page_events_list_add_event: 'Созвать встречу',
	page_event_edit_title: 'Редактирование встречи',
	page_event_add_title: 'Созвать встречу',

	page_user_blog_empty_title: 'Блог пользователя',
	page_group_blog_empty_title: 'Блог группы',

	title: 'Название',
	description: 'Описание',


	edt: 'Ред.',
	menu_my_page: 'Моя Страница',
	menu_my_friends: 'Мои Друзья',
	menu_my_photos: 'Мои Фотографии',
	menu_my_video: 'Мои Видеозаписи',
	menu_my_audio: 'Мои Аудиозаписи',
	menu_my_messages: 'Мои Сообщения',
	menu_my_clubs: 'Мои Группы',
	menu_my_events: 'Мои Встречи',
	menu_feed: 'Мои Новости',
	menu_settings: 'Мои Настройки',

	block_quick_search_search: 'Поиск по сайту',
	block_quick_search_to_find: 'Найти',

	error_service_not_available: 'Приносим извинения. В данный момент сервис недоступен.',

	page_index_describe_header: 'Социальная сеть. Файловое хранилище. Система управления взаимоотношениями с клиентами. Eforb - мы открыты каждому!',
	page_index_describe_text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an  unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,  remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop  publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
	widget_greeting_social_network: 'Социальная сеть',
	widget_greeting_free_crm: 'Бесплатная CRM',
	widget_greeting_filebox: 'Хранилище файлов',
	widget_greeting_open_api: 'Открытое API',
	widget_greeting_buisness_platform: 'Бизнес-платформа',
	widget_greeting_social_network_description: 'Универсальное средство общения  и поиска знакомых. Здесь можно  посмотреть на людей, показать  себя, поделиться мыслями, узнать  что нового у старых друзей  и поискать друзей новых.',
	widget_greeting_free_crm_description: 'Мощная CRM-система, которая  позволяет централизовано  управлять: информацией о  клиентах, продажами, закупками,  финансами, задачами и кадрами.  Является незаменимым помощником  менеджеров, повышает  эффективность их работы.  Дает возможность руководителю  осуществлять анализ и контроль  работы предприятия.',
	widget_greeting_filebox_description: 'Eforb filebox – удобный бесплатный  способ синхронизации файлов  между устройствами',
	widget_greeting_open_api_description: 'Вы можете создать любое  приложение и использовать API  Eforb для доступа и обмена  информацией с серверами Eforb.   Вы можете использовать любое  количество собственных серверов  и любыми средствами  монетизировать собственные  приложения.   API дает разработчикам сотни  возможностей и позволяет  создавать интересные,  интерактивные и популярные  приложения.',
	widget_greeting_buisness_platform_description: 'Бизнес-платформа позволяет централизовано  управлять: информацией о  клиентах, продажами, закупками,  финансами, задачами и кадрами.',

	page_index_join_the_team: 'Присоединяйтесь к команде профессионалов!',

	page_messages_title: 'Сообщения',
	page_messages_incoming_title: 'Входящие',
	page_messages_outcoming_title: 'Исходящие',
	page_messages_from_user_title: 'Сообщения от пользователя',
	page_messages_awnser: 'Ответить',
	page_messages_write: 'Написать',
	page_messages_subject: 'Тема сообщения',
	page_messages_text: 'Сообщение',
	page_messages_reciever: 'Получатель',
	page_messages_symbols_left: 'Осталось знаков: ',
	page_messages_symbols_overprint: 'Допустим объём сообщения превышен на: ',
	page_messages_history: 'История сообщений',
	page_messages_write_a_message: 'Написать сообщение',
	page_messages_delete: 'Удалить',
	page_messages_no_messages: 'У вас нет сообщений.',
	page_messages_message_for: 'Сообщение для: ',

	page_messages_edit_private_who_can_write_me: 'Кто может писать мне?',
	page_messages_edit_private_no_one: 'Никто',
	page_messages_edit_private_friends: 'Друзья',
	page_messages_edit_private_all: 'Все',
	page_profile_private_edit_title: 'Настройки приватности',


	loc_and: 'и',


	//EVENT_UPDATE_PROFILE = 0x02
	feed_update_profile: 'Вы обновили свой профиль.',
	//EVENT_FRIEND_ACCEPT = 0x04
	feed_friendship: ' теперь друзья',
	//EVENT_GROUP_JOIN = 0x08
	feed_join_group: 'Вступил в ',
	//EVENT_GROUP_QUIT = 0x09
	feed_quit_group: 'Вышел из группы ',
	//EVENT_EVENT_JOIN = 0x11
	feed_join_event: 'Решил идти на встречу ',
	//EVENT_EVENT_QUIT = 0x12
	feed_quit_event: 'Решил не ходить на встречу ',


	//WIDGET WALL
	wall: 'Стена',
	widget_wall_whats_new: 'Что нового?',
	widget_wall_public_message: 'Публичное сообщение',
	widget_wall_to_comment: 'Комментировать',
	widget_wall_comment_placeholder: 'Ваш комментарий',
	widget_wall_allposts: 'Все посты',
	widget_wall_favorites: 'Избранное',
	widget_wall_photo: 'Фото',
	widget_wall_video: 'Видео',
	widget_wall_audio: 'Аудио',
	widget_wall_references: 'Ссылки',
	widget_wall_polls: 'Опросы',
	


	edit_event: 'Редактировать встречу',
	edit_group: 'Редактировать группу',

	page_event_not_found_title: 'Встреча не найдена',
	page_group_not_found_title: 'Группа не найдена',

	edit_members: 'Редактировать состав',
	invite: 'Пригласить',
	edit_administration: 'Редактировать руководство',

	event_place: 'Место встречи',
	event_start_date: 'Начало встречи',
	event_end_date: 'Окончание встречи',
	event_city: 'Город',
	event_type: 'Тип',

	loc_delete: 'Удалить',

	page_group_members_title: 'Состав группы',
	page_group_requests_title: 'Заявки в группу',
	page_group_administration_title: 'Администрация группы',
	page_group_invite_title: 'Пригласить в группу',
	page_group_invites_title: 'Приглашения в группу',

	page_event_members_title: 'Состав встречи',
	page_event_administration_title: 'Администрация встречи',
	page_event_invite_title: 'Пригласить на встречу',
	page_event_invites_title: 'Приглашения на встречу',
	page_people_list_invites_title: 'Приглашения',
	page_people_list_no_people: 'Сейчас тут нет людей.',
	page_people_list_members: 'Список участников',
	page_people_list_invite: 'Пригласить',
	page_people_list_invites: 'Приглашения',
	page_people_list_requests: 'Заявки',
	page_people_list_administration: 'Администрация',
	page_people_list_remove_invite: 'Отменить приглашение',
	page_people_list_remove_from_administation: 'Удалить из администрации',
	page_people_list_remove_member: 'Удалить из состава',
	page_people_list_accept_request: 'Принять заявку',
	page_people_list_decline_request: 'Отклонить заявку',
	page_people_list_add_to_administation: 'Добавить в администрацию',

	pagination_page: 'Страница',
	pagination_next_page: 'Следующая страница',
	pagination_previous_page: 'Предыдущая страница',
	pagination_last_page: 'Последняя страница',
	pagination_first_page: 'Первая страница',
	pagination_more: 'Ещё',
	pagination_show_more: 'Показать ещё',

	link_more: 'Подробнее',

	group_private: 'Закрытая (приватная) группа',

	//LISTS
	family: 'Семья',
	work: 'Работа',
	school: 'Школа',
	page_friends_add_list: 'Добавить список',
	page_friends_add: 'Добавить',
	page_friends_list_name: 'Название списка',

	page_friend_list_editor_edit_list: 'Редактировать список',
	page_friend_list_editor_delete_list: 'Удалить список',
	page_friend_list_editor_view_list: 'Посмотреть список',

	page_groups_requests_title: 'Приглашения',
	button_accept_group: 'Вструпить в группу',
	button_decline_group: 'Не вступать',

	user_not_found: 'Пользователь не найден',

	page_photo_title: 'Фотографии',
	page_media_next: 'Следующее',
	page_media_previous: 'Предыдущее',
	page_media_upload: 'Загрузить',
	page_media_upload_more: 'Загрузить ещё',
	page_media_album: 'Альбом',
	page_photo_album: 'Фотоальбом',
	page_audio_album: 'Плейлист',
	page_video_album: 'Коллекция видео',
	page_audio_title: 'Аудиозаписи',
	page_audio_record: 'Аудиозапись',
	page_video_title: 'Видеозаписи',
	page_video_record: 'Видеозапись',

	loc_edit: 'Редактировать',
	uploaded: 'Загружено',
	author: 'Автор',
	added: 'Добавлено',
	changed: 'Изменено',
	pin_some_people: 'Отметить людей',
	page_photo_album_edit_title: 'Редактировать альбом',
	page_photo_edit_title: 'Редактировать фотографии в альбоме',
	page_photo_album_edit_title: 'Редактировать альбом',
	page_album_edit_title: 'Редактировать альбом',
	page_photo_album_delete: 'Удалить альбом',
	page_photo_album_add: 'Добавить альбом',
	page_photo_album_add_title: 'Создать альбом',
	page_photo_make_cover: 'Поставить обложкой альбома',
	page_photo_no_photos: 'Тут ещё нет фотографий',
	page_photo_no_albums: 'Тут ещё нет альбомов',
	page_photo_add_title: 'Добавить фотографии',
	page_photo_no_pin_friends: 'У вас нет друзей, которых вы можете отметить на этой фотографии',

	page_audio_default_title: 'Все аудиозаписи',
	page_audio_album_delete: 'Удалить плейлист',
	page_audio_album_add: 'Добавить плейлист',
	page_audio_album_add_title: 'Создать плейлист',
	page_audio_no_audios: 'Тут ещё нет аудио',
	page_audio_no_albums: 'Тут ещё нет плейлистов',
	page_audio_add_title: 'Добавить аудио',
	page_audio_all_albums: 'Плейлисты',
	page_audio_edit: 'Редактировать аудиозаписи',
	page_audio_album_edit: 'Редактировать плейлист',
	page_audio_album_edit_title: 'Редактирование плейлиста',

	page_video_album_edit_title: 'Редактировать видеоколлекцию',
	page_video_edit_title: 'Редактировать фотографии в видеоколлекции',
	page_video_album_edit_title: 'Редактировать видеоколлекцию',
	page_video_album_delete: 'Удалить видеоколлекцию',
	page_video_album_add: 'Добавить видеоколлекцию',
	page_video_album_add_title: 'Создать видеоколлекцию',
	page_video_make_cover: 'Поставить обложкой видеоколлекцию',
	page_video_no_videos: 'Тут ещё нет видеороликов',
	page_video_no_albums: 'Тут ещё нет видеоколлекций',
	page_video_add_title: 'Добавить видеоролики',
	page_video_no_pin_friends: 'У вас нет друзей, которых вы можете отметить на этом видеоролике',
	page_video_back_to_album: 'Вернуться к видеоколлекции',
	page_video_all_albums: 'Видеоколлекции',
	page_video_default_title: 'Все видеозаписи',
	page_video_album_edit: 'Редактировать видеокллекцию',

	widget_photo_albums_title: 'Фото-альбомы',

	widget_photo_album: 'альбом',
	widget_photo_albums: 'альбомов',
	widget_photo_albums_1: 'альбом',
	widget_photo_albums_a: 'альбома',

	total: 'Всего',
	widget_photo_album_no_cover: 'Фотоальбом',
	widget_photo_title: 'Фотографии',
	widget_audio_title: 'Аудиозаписи',
	widget_video_title: 'Видеозаписи',
	widget_video_no_videos: 'Тут ещё нет видео. ',
	widget_audio_no_audios: 'Тут ещё нет аудиозаписей. ',
	widget_photo_no_photos: 'Тут ещё нет фотографий. ',
	widget_photo_albums_no_albums: 'Тут ещё нет альбомов. ',
	page_audio_edit_title: 'Редактировать плейлист ',
	page_audio_edit_back: 'Вернуться к аудиозаписям',

	page_photo_tag_its_you: 'Фотографии на которых вы отмечены',
	page_photo_tag_title: 'Фотографии на которых отмечен',

	page_discussion_add_title: 'Добавить обсуждение',
	page_discussion_edit_title: 'Редактировать обсуждение',
	page_discussion_start_from_parent: 'Начато из обсуждения',
	page_discussion_start_from_here: 'Начать новое обсуждение с этого поста',
	page_discussion_all_in_group: 'все обсуждения в группе',
	page_discussion_groups_all: 'Обсуждения группы ',
	to_view: 'Просмотреть',

	page_calendar_events: 'Вы собирались пойти на',
	page_calendar_title: 'Каледарь',
	page_calendar_no_events_this_month: 'В этом месяце ни чего не намечается',
	page_calendar_birthdays: 'Дни рожденья',

	month_1: 'январь',
	month_2: 'февраль',
	month_3: 'марта',
	month_4: 'апрель',
	month_5: 'май',
	month_6: 'июнь',
	month_7: 'июль',
	month_8: 'август',
	month_9: 'сентябрь',
	month_10: 'октябрь',
	month_11: 'ноябрь',
	month_12: 'декабрь',

	page_discussion_no_discussions: 'В этой группе ещё нет обсуждений',
	widget_discussions_no_discussions: 'Тут ещё нет обсуждений',
	widget_discussions_title: 'Обсуждения',

	widget_poll_title: 'Голосование',
	widget_poll_add: 'Добавить голосование',
	widget_poll_new_answer: 'Добавить ответ',
	widget_poll_add_title: 'Описание опроса',
	widget_poll_to_vote: 'Голосовать',

	page_post_edit_title: 'Редактировать запись ',
	page_post_add_title: 'Новая запись ',
	page_blog_edit_title: 'Редактировать блог ',
	page_blog_not_found_title: 'Блог не найден',
	page_blog_blog: 'Блог',
	page_blog_comments: 'Комментарии',
	page_blog_add_new_post: 'Добавить новую запись',
	page_blog_no_posts: 'Тут ещё нет записей',

	menu_my_calendar: 'Мой Каледарь',
	menu_my_blog: 'Мой Блог',

	photo_with: 'Фото, на котором есть ',
	video_with: 'Видео, на котором есть ',
	announce_event: 'Рассказать о встрече',
	announce_group: 'Рассказать о группе',
	announce: 'Рассказать друзьям',

	feed_user_was_tagged: ' был отмечен на фотографиях: ',
	feed_audio_album: 'Плейлист',
	feed_video_album: 'Видеоколлекция',
	feed_photo_album: 'Фото-альбом',
	feed_in_blog: 'в блоге',
	feed_blog_post: 'Запись',
	feed_blog: 'Блог',
	feed_discussion: 'Обсуждение',
	feed_show_same: 'Показать похожие',
	feed_hide_same: 'Скрыть похожие',
	widget_poll_add_poll: 'Добавить опрос',

	widget_blog_title: 'Блог',
	widget_blog_no_posts: 'Ещё нет записей в блоге',

	page_tagged_you_was_tagged: 'Вы были отмечены на ',
	page_photo_has_tagged_you: ' отметил вас на фотографии ',
	page_video_has_tagged_you: ' отметил вас на видео ',
	page_tagged_acsept: 'Подтвердить',
	page_tagged_decline: 'Это не я!',
	loc_someone: 'Кто-то',


	attach_button: 'Прикрепить',
	attach_photo: 'Фото',
	attach_photo_album: 'Фотоальбом',
	attach_video: 'Видео',
	attach_audio: 'Аудио',
	attach_poll: 'Опрос',
	attach_map: 'Карту',

	enable_delayed_message: 'Отправить это сообщение позже',
	send_delayed_message_after: 'Отправить это сообщение ',

	enable_poll: 'Добавить голосование',

	loc_at: 'в',

	widget_like_delete: 'Не нравится',
	widget_like_add: 'Мне нравится',
	widget_like_people_liked: 'Этим людям понравилось',

	page_feed_privacy_edited: 'Вы изменили настройки приватности.',

	upload_avatar: 'Загрузить новый аватар',

	group_access_type: 'Тип группы',
	group_access_public: 'Публичная (открытая)',
	group_access_restricted: 'Ограниченная',
	group_access_private: 'Частная',
	event_access_type: 'Тип события',
	event_access_public: 'Публичное (открытое)',
	event_access_restricted: 'Ограниченное',
	event_access_private: 'Частное',
	group_wall_mode: 'Стена',
	wall_off: 'Отключена',
	wall_public: 'Открытая',
	wall_restricted: 'Ограниченная',
	wall_private: 'Закрытая',
	group_video_mode: 'Видеозаписи',
	video_off: 'Отключены',
	video_public: 'Открытые',
	video_restricted: 'Ограниченные',
	group_audio_mode: 'Аудиозаписи',
	audio_off: 'Отключены',
	audio_public: 'Открытые',
	audio_restricted: 'Ограниченные',
	group_photo_mode: 'Фотоальбомы',
	photo_off: 'Отключены',
	photo_public: 'Открытые',
	photo_restricted: 'Ограниченные',
	group_blog_mode: 'Блог',
	blog_off: 'Отключен',
	blog_public: 'Включен',
	group_discussions_mode: 'Дискуссии',
	discussions_off: 'Отключены',
	discussions_public: 'Включены',
	page_uiobok: 'Да вы же уёбок!!!',
	page_messages_mark_as_viewed: 'Прочитано'
}